/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Random;

public class App {


  public static void main(String[] args) throws IOException {

//
   readJsonFile();
  }


  public static void readJsonFile() throws IOException {
    String path="recentquotes.json";
    BufferedReader  reader = Files.newBufferedReader(Paths.get("C:\\Users\\maria\\Desktop\\testJava\\quotes\\app\\src\\main\\resources\\recentquotes.json"));
//
//
    // make a List of type Quotes then
    //convert JSON array to list of users
    List<Quotes> users = new Gson().fromJson(reader, new TypeToken<List<Quotes>>() {}.getType());
    // select a random number of the indexes of the list and pick one:
    Random rand = new Random();
    System.out.println(users.get(rand.nextInt(users.size())));

    // if we want to print it all :
//    users.forEach(System.out::println);
    reader.close();
  }

  }





