/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quotes;

import com.google.common.reflect.TypeToken;
import com.google.gson.Gson;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.List;
import java.util.Random;

public class App {


  public static void main(String[] args) throws IOException {

//      try {
//
//        Gson gson = new Gson();
//        // convert JSON string to User object
//        Reader reader = Files.newBufferedReader(Paths.get("recentquotes.json"));
//        // here we will convert  Json into file :
//        Map<?, ?> map = gson.fromJson(reader, Map.class);
//        // and then :
//        for (Map.Entry<?, ?> entry : map.entrySet()) {
//
//          System.out.println(entry.getKey() + "=" + entry.getValue());
//        }
//      }catch (Exception ex) {
//        ex.printStackTrace();
//      }

   readJsonFile();
  }


  public static void readJsonFile() throws IOException {
    String path="recentquotes.json";
    BufferedReader  reader = Files.newBufferedReader(Paths.get("C:\\Users\\maria\\Desktop\\testJava\\quotes\\app\\src\\main\\resources\\recentquotes.json"));
//    String output = "";
//    StringBuilder stringBuilder = new StringBuilder();
//
//    while((output = reader.readLine()) != null){
//      stringBuilder.append(output);
//    }
//
//    return stringBuilder.toString();
    List<Quotes> users = new Gson().fromJson(reader, new TypeToken<List<Quotes>>() {}.getType());
    Random rand = new Random();
    System.out.println(users.get(rand.nextInt(users.size())));


//    users.forEach(System.out::println);
    reader.close();
  }

  }





